### ISSUE TITLE
Зачем count и cost?

### ISSUE THREAD

**Issue by coursar** [AliAlievALive/dbUlmart#20]
https://github.com/AliAlievALive/dbUlmart/blob/ddd2ff98ad2301ee992c157753fefaae0feba835/src/main/resources/db.sql#L18-L20

**Comment by AliAlievALive** [comment]
count для подсчета количества купленного продукта, а cost для сохранения цены продукта на момент заказа

**Comment by coursar** [comment]
А в sales тогда что?

**Comment by AliAlievALive** [comment]
orders_id - для доступа к определенному заказу
product_id - для просмотра продукта (но цену могли изменить с момента заказа, поэтому в orders хранится цена на момент заказа)
number - для подсчета продаж
